### PR TITLE
Use new & improved match pattern.

### PR DESCRIPTION
**Pull request by phungleson**
Use new & improved match pattern.

It looks a bit cleaner and newer.

### CODE REVIEW

**Comment by cuviper** [comment]
We intentionally keep conservative `rustc` compatibility.  Given that this PR is just cosmetic, with no new functionality, I think it's not worth forcing the upgrade.

**Comment by phungleson** [comment]
Thanks, that's what I thought when I see travis.yml.

**Comment by cuviper** [comment]
No, all crates of a project still have to use the same compiler version.  A particular compiler like `rustc 1.30.0` will support both 2015 and 2018 edition crates.  The new edition changes the language somewhat with breaking changes, so a crate has to declare which edition they are written for, but overall everything is still compiled together.

**Comment by cuviper** [comment]
The blog post on editions may help: https://blog.rust-lang.org/2018/07/27/what-is-rust-2018.html

**Pull request closed without merging**
