### PR TITLE
Enable feature to have an untagged serde representation

### PR DESCRIPTION
**Pull request by aledomu**

### CODE REVIEW

**Comment by cuviper** [comment]
Please see prior discussions in #22 and #46 -- I don't think we want to force a global effect. `Either` might be used in multiple places in a crate dependency graph, but features are unified by cargo, so it will make the same choice everywhere.

**Comment by aledomu** [comment]
It won't break existing users even with that global effect, because the behaviour of "serde" remains the same. And well, the burden of whether that global effect is enforced or not by other libraries is on those other libraries; they have to re-expose in some way that feature. That's how it's done when these kind of implementation details might affect the users of your library. However, in the light of this possibility I strongly think that it should be explained in the docs.

**Comment by cuviper** [comment]
The behavior of "serde" is not the same, because cargo will unify all features to make just one semver-compatible build of `either`. For example, the dependency tree could look something like this:

- `application`
  - `foo`
    - `either = { version = "1", features = ["serde"] }`
  - `bar`
    - `either = { version = "1", features = ["serde_untagged"] }`

There will be just one build of `either` with combined `features = ["serde", "serde_untagged"]`. This is why it's often said that cargo features must be additive. So your `#[cfg_attr(feature = "serde_untagged", serde(untagged))]` will now be enabled for **all** serializations of `Either`, which is not what `foo` wanted. That may break its access to persistent data, or break interoperability with another source (still tagged), or break in any other way in which the serialization format is expected to be consistent.

**Comment by aledomu** [comment]
Oh I see. I'll follow the discussion in those issues.

**Pull request closed without merging**
