### PR TITLE
Write more general implementations of PartialEq/PartialOrd

### PR DESCRIPTION
**Pull request by Twey**
This pull request manually implements `PartialEq` and `PartialOrd` to extend them for heterogeneous equalities.

It's debatable whether `Ord` should remain implemented (I'd be happier to return `None` for `Left(_).partial_cmp(Right(_))`/`Right(_).partial_cmp(Left(_))`), but for backwards compatibility with the derived implementation I've left it in.

### CODE REVIEW

**Comment by bluss** [comment]
Due to type inference breakage (see travis failure for example), I don't think this is worth it unfortunately.

**Comment by Twey** [comment]
:cry:
That does seem reasonable.

How averse are you to using specialization to solve that?

**Comment by bluss** [comment]
I think we should not use unstable features in this stable library, even if it's optional. Version numbers don't mean anything if we have unstable features..

These comments are kind of redundant since I'm not very keen on the change but:

* If you add new functionality, it needs a test
* If you add crate features, please fix travis.yml to test with and without that

**Comment by bluss** [comment]
Thanks anyway! This PR was declined because:

- Changing notion of equality to be partial is not a wanted feature, we want Ord
- Generalizing in the style of `A: PartialEq<B>` is nice to have but breaks too much for too little gain (type inference related breaks only).

**Pull request closed without merging**
