### PR TITLE
Implement the io::Seek trait

### PR DESCRIPTION
**Pull request by Kerollmops**
This pull request implements [the io::Seek trait](https://doc.rust-lang.org/std/io/trait.Seek.html) on Either when `L` and `R` implements it.

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey @cuviper, Would it be possible to take a look at this PR, please? Thanks in advance! ❤️

**Comment by gwy15** [comment]
I finished my own impl before running into this PR, LGTM but perhaps a test case would make it better :)

here's my impl

https://github.com/gwy15/either/commit/bf916ec7f2953dd8a7ece597243b46d8beaa9bca#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R1109

**Comment by cuviper** [comment]
The required `Seek::seek` seems fine. The other methods are more recently stabilized, so we'll have to think about MSRV, like we're discussing in #66. Or if you don't *need* the specialized versions of those, you can just let the trait-provided implementations do their approximation.

**Comment by Kerollmops** [comment]
You are right, I just removed the two methods that were implemented recently to keep the crate MSRV under _1.55.0_. 
Thank you, I forgot about this.

**Comment by cuviper** [comment]
The new CI found a few issues, but I've fixed them. Thanks!

**Pull request merged**
