### PR TITLE
Documentation, inline-hints, `either`, `map_left` and `map_right`

### PR DESCRIPTION
**Pull request by m4rw3r**
Added documentation for the methods defined on `Either`, and a few more convenience methods to bring it closer to the functionality provided by `Option` and `Result`.

### CODE REVIEW

**Comment by bluss** [comment]
Hi, thanks. Aren't all the inline hints redundant? All the items are generic.

**Comment by m4rw3r** [comment]
@bluss Are we sure that is not just an implementation detail of rustc, or is it specified somewhere?

**Comment by bluss** [comment]
Right. And inlining or not is just an implementation detail too, isn't it?

I do think the inlining story is changing a bit with incremental compilation actually, so I'm not fully up to date on that. I don't see much value in adding these inline attributes though.

**Comment by m4rw3r** [comment]
@bluss You got a point, removing them, we can always add them later if necessary.

**Comment by bluss** [comment]
Examples headings.. hm. I never use those in my crates, it still doesn't work well in rustdoc's style.

**Comment by bluss** [comment]
:tada:

**Pull request merged**
