### PR TITLE
Add an 'untagged' feature to have Either be marked as untagged for serde

### PR DESCRIPTION
**Pull request by capitnflam**
It would be nice to be able to serialize/deserialize in an untagged manner.

### CODE REVIEW

**Comment by cuviper** [comment]
I think it's a problem that this has global effect.  If _any_ crate in a dependency graph activates either/untagged, then _all_ serializations of `Either` will be changed thus.

**Comment by capitnflam** [comment]
I see what you mean, this can effectively cause problems.
But I don't see any other way for the following code to work:
```rust
extern crate serde;
#[macro_use]
extern crate serde_derive;
extern crate serde_json;
extern crate either;

use either::Either;
use serde_json::Error;

#[derive(Debug, Deserialize)]
struct Foo {
    bar: String,
    baz: Option<Either<String, bool>>,
}

fn tryme(name: &str, data: &str) {
    let value: Result<Foo, Error> = serde_json::from_str(data);

    match value {
        Ok(v) => println!("Success: {}: {:?}", name, v),
        Err(e) => println!("Failure: {}: {:?}", name, e),
    }
}

fn main() {
    let data1 = r#"{
        "bar": "test1"
    }"#;
    let data2 = r#"{
        "bar": "test2",
        "baz": "this should work"
    }"#;
    let data3 = r#"{
        "bar": "test3",
        "baz": true
    }"#;
    let data4 = r#"{
        "bar": "test4",
        "baz": null
    }"#;
    let data5 = r#"{
        "bar": "test5",
        "baz": 42
    }"#;

    tryme("test1", data1);
    tryme("test2", data2);
    tryme("test3", data3);
    tryme("test4", data4);
    tryme("test5", data5);
}
```
I would expect this code to output:
```
Success: test1: Foo { bar: "test1", baz: None }
Success: test2: Foo { bar: "test2", baz: Some(Left("this should work")) }
Success: test3: Foo { bar: "test3", baz: Some(Right(true)) }
Success: test4: Foo { bar: "test4", baz: None }
Failure: test5: ErrorImpl { code: Message("data did not match any variant of untagged enum Either"), line: 4, column: 5 }
```

Any idea on how I could achieve this?

**Comment by cuviper** [comment]
Maybe you could do this with a [remote derive](https://serde.rs/remote-derive.html)?  So you'd define a local `MyEither` definition with `#[serde(untagged)]` and `#[serde(remote = "Either")]`, and then use `#[serde(with = "MyEither")]` on the real field.  It's further complicated by having an `Option` in the mix, but I'll bet there's still a way to work around this.

**Comment by bluss** [comment]
Thanks for this, but I'll close since we can't integrate this and keep compatibility for all users. I hope some solution came out of the ideas @cuviper had.

**Comment by jesskfullwood** [comment]
Hope this might be reconsidered at some point - I consider this to be one of the major use-cases for this library.

**Comment by cuviper** [comment]
I still think it's a problem that untagging has a global effect. Maybe you could ask the serde developers for a way to derive untagging on a particular field?

> So you'd define a local `MyEither` definition with `#[serde(untagged)]` and `#[serde(remote = "Either")]`, and then use `#[serde(with = "MyEither")]` on the real field. It's further complicated by having an `Option` in the mix, but I'll bet there's still a way to work around this.

I played with this a little -- it's easy enough for `Either` alone, but I couldn't get a derived `impl` working with `Option`. I think you'd have to write a manual `#[serde(with = "...")]` method with a `deserialize_option` visitor that maps the untagged version to `Either`.

**Comment by cuviper** [comment]
Here's a version which works as intended for all of @capitnflam's tests:

```rust
#[derive(Debug, Deserialize)]
struct Foo {
    bar: String,
    #[serde(default, deserialize_with = "deserialize_option_untagged_either")]
    baz: Option<Either<String, bool>>,
}

fn deserialize_option_untagged_either<'de, D, L, R>(
    deserializer: D,
) -> Result<Option<Either<L, R>>, D::Error>
where
    D: Deserializer<'de>,
    L: Deserialize<'de>,
    R: Deserialize<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    // shadowing the same name improves error messages
    enum Either<L, R> {
        Left(L),
        Right(R),
    }

    Option::<Either<L, R>>::deserialize(deserializer).map(|opt| {
        opt.map(|either| match either {
            Either::Left(left) => self::Either::Left(left),
            Either::Right(right) => self::Either::Right(right),
        })
    })
}
```

That's not as nice as a normal `derive`, but it's not as much boilerplate as I thought it would need.

PS: You don't even need the `either/serde` feature enabled for this!

**Comment by aledomu** [comment]
Maybe this should be made the default representation in a major version change? Because it doesn't make sense to tag an enum that is meant to be a generic data structure. Or maybe make a different crate altogether based on this?

**Pull request closed without merging**
