### PR TITLE
gitignore: ignore target as a symlink

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by bluss** [comment]
I don't quite see the point of this one. Will it continue to work if I use `/target` here instead? That's more correct (only match in the root)

**Comment by mathstuf** [comment]
Sorry for the delay; just got back from an extended vacation. See rust-lang/cargo#3997 for reasons that `/target` isn't used. And rust-lang/cargo#4944 for my change to support having `target` be a symlink (I store build artifacts on a separate partition on my machines).

**Comment by mathstuf** [comment]
Oh, it is `/target` now. I'll update to match that too.

**Comment by bluss** [comment]
Thanks!

**Pull request merged**
